Add node exporter
pyronear/pyro-sys-setup pull request #19
Opened 2021-05-09 10:44 UTC by fe51

This PR aims at adding playbook to set up a node exporter on each rpis.

Hence, after running the playbook, metrics of pis are available on port 9100 via their hostname or ip (ex:  http://pimain.local:9100/metrics or http://192.168.1.64:9100/metrics)

- Tasks in the playbook :
  - According to rpi architecture, download an copy to `/usr/local/bin/` the relevant version of the [prometheus node exporter](https://github.com/prometheus/node_exporter/releases)
  - Create node_exporter user
  - Create node_exporter service from template
  - Start and enable the service

- In the future, gathered machine metrics could be updated (see https://github.com/prometheus/node_exporter#collectors or http://manpages.ubuntu.com/manpages/groovy/man1/prometheus-node-exporter.1.html for details ). To date, metrics we wanted are available :
  - <u>Temperature</u> with `node_thermal_zone_temp`
  - <u>RAM</u> with `node_memory_MemAvailable_bytes` (many are available)
  - <u>Cpu</u>, a lot of metrics are avaialble, will have to choose relevant ones when building dashboards

A another PR setting up nginx (allowing to requests on 9100 to any pi metrics from bastion) will come up soon. 

Feedbacks are welcome (Especially, condition about architecture, implementation works, but that might be a cleaner way to do it)

2021-05-09 11:41 UTC, chloeskt requested changes
Hello @fe51, thank you for this PR ! 
Overall it is a nice one, I just have some side comments :)

2021-05-09 11:41 UTC, chloeskt commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
Do you truly need to use "sudo" here ?

2021-05-09 11:41 UTC, chloeskt commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
Do you truly need to use "sudo" here ?

2021-05-09 11:41 UTC, chloeskt commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
Do you truly need to use "sudo" here ?

2021-05-09 11:41 UTC, chloeskt commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
Do you truly need to use "sudo" here ?

2021-05-09 11:41 UTC, chloeskt commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
Do you truly need to use "sudo" here ?

2021-05-09 11:41 UTC, chloeskt commented on playbooks/setup_node_exporter_rpi.yml
> +      ansible.builtin.copy:
Do you think that there is a way to merge the two task in a single one ? Namely unarchive and copy. Would it be possible to unarchive directly in the wanted directory ? 

That would be nicer !

2021-05-10 10:03 UTC, fe51 commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
no indeed!

2021-05-10 10:03 UTC, fe51 commented on playbooks/setup_node_exporter_rpi.yml
> +      ansible.builtin.copy:
Hum, would be nice indeed but as long as the copy only concerns a file from the archive, not sure this is possible directly.

2021-05-10 10:03 UTC, fe51 commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
yes otherwise cannot access the dedicated folder

2021-05-10 10:03 UTC, fe51 commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
no indeed

2021-05-10 10:03 UTC, fe51 commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
yes, same as previous comment

2021-05-10 10:03 UTC, fe51 commented on playbooks/setup_node_exporter_rpi.yml
> +      become: true
yes, to access system files

2021-05-10 10:05 UTC, fe51 commented
Hi @chloeskt, thanks for the review ! I have answered your comments !

2021-05-10 18:04 UTC, chloeskt approved these changes
Alright, thanks ! all good

2021-05-11 07:15 UTC, merged